########################################################################################################################
#                                                                                                                      #
#                                                     FastTravel                                                       #
#                                                   Semi-vanilla MC                                                    #
#                                                  Author : Alen_Alex                                                  #
########################################################################################################################

##When a player click for teleportation, how many sec he should wait before a teleportation commence
teleportation-delay-in-sec: 5

##This cool-down will be placed after a player gets teleported successfully. once active he/she will have to wait for X
##sec to initiate next teleportation
cooldown-between-teleportation-in-sec: 10

square-map-icon-size: 40
##GUI Configuration
#name: Name of the GUI
#rows: no of rows the plugin should have.
##NOTE: It should be less than 5, as the plugin adds a row as filler in bottom .
gui:
  name: "Waypoints"
  rows: 5
  buttons:
    unlocked:
      name: "<green>%name%"
      lore-to-add-at-last:
        - "<green>Click to visit the waypoint"
    locked:
      name: "<red>%name%"
      lore-to-add-at-last:
        - "<red>Locked! - visit %x% %z% to unlock."
    additional:
      enabled: true
      item: "base64:eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2I1NmU0OTA4NWY1NWQ1ZGUyMTVhZmQyNmZjNGYxYWZlOWMzNDMxM2VmZjk4ZTNlNTgyNDVkZWYwNmU1ODU4YyJ9fX0="
      name: "<gray>Home"
      lore:
        - "<white>Click to teleport back to home"
      command: "home"
  filler:
    BLACK_STAINED_GLASS_PANE:
      - 0
      - 1
      - 7
      - 8
      - 9
      - 10
      - 16
      - 17
      - 18
      - 19
      - 25
      - 26
      - 27
      - 28
      - 34
      - 35
      - 36
      - 37
      - 43
      - 44


messages:
  help:
    header: "<yellow><strikethrough>                         <reset> Waypoint Help <yellow><strikethrough>                         <reset>"
    ##Available Placeholder:
    #%command% -> Parses the command
    #%description% -> Parses the description
    command: "<gold>%command%<white>: %description%"
    footer: "<yellow><strikethrough>                                                                  <reset>"
  on-teleport-queue: <yellow>Teleporting in 5 seconds, don\'t move...
  teleport-commencing: "<yellow>Teleporting..."
  teleport-cancelled:
    on-move: "<red>Pending teleportation request cancelled."
    on-new-request: "<red>Pending teleportation request cancelled in favour for new teleportation request."
  ## Available Placeholder: %waypoint_name% -> Name of the waypoint
  waypoint-discovered: "<green>You discovered %waypoint_name%! Now you can teleport to this waypoint!"
  waypoint-locked: "<red>You must visit this location to unlock this waypoint."
  ## Available Placeholder: %cool-down% -> Cooldown in secs
  player-in-cooldown: "<red>you are in cool-down for %cool-down% secs. Try later!"
  no-permission: "<red>You do not have permission to do that."
  unknown-command: "<red>Unknown command"