########################################################################################################################
#                                                                                                                      #
#                                                     FastTravel                                                       #
#                                                   Semi-vanilla MC                                                    #
#                                                  Author : Alen_Alex                                                  #
########################################################################################################################

##When a player click for teleportation, how many sec he should wait before a teleportation commence
teleportation-delay-in-sec: 5